<!DOCTYPE html>
<!-- Generated by pkgdown: do not edit by hand --><html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Spread of a pathogen in a discrete structured population • nosoi</title>
<!-- favicons --><link rel="icon" type="image/png" sizes="16x16" href="../favicon-16x16.png">
<link rel="icon" type="image/png" sizes="32x32" href="../favicon-32x32.png">
<link rel="apple-touch-icon" type="image/png" sizes="180x180" href="../apple-touch-icon.png">
<link rel="apple-touch-icon" type="image/png" sizes="120x120" href="../apple-touch-icon-120x120.png">
<link rel="apple-touch-icon" type="image/png" sizes="76x76" href="../apple-touch-icon-76x76.png">
<link rel="apple-touch-icon" type="image/png" sizes="60x60" href="../apple-touch-icon-60x60.png">
<!-- jquery --><script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script><!-- Bootstrap --><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha256-916EbMg70RQy9LHiGkXzG8hSg9EdNy97GazNG/aiY1w=" crossorigin="anonymous">
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha256-U5ZEeKfGNOja007MMD3YBI0A3OSZOQbeG6z2f2Y0hu8=" crossorigin="anonymous"></script><!-- Font Awesome icons --><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.7.1/css/all.min.css" integrity="sha256-nAmazAk6vS34Xqo0BSrTb+abbtFlgsFK7NKSi6o7Y78=" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.7.1/css/v4-shims.min.css" integrity="sha256-6qHlizsOWFskGlwVOKuns+D1nB6ssZrHQrNj1wGplHc=" crossorigin="anonymous">
<!-- clipboard.js --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.4/clipboard.min.js" integrity="sha256-FiZwavyI2V6+EXO1U+xzLG3IKldpiTFf3153ea9zikQ=" crossorigin="anonymous"></script><!-- headroom.js --><script src="https://cdnjs.cloudflare.com/ajax/libs/headroom/0.9.4/headroom.min.js" integrity="sha256-DJFC1kqIhelURkuza0AvYal5RxMtpzLjFhsnVIeuk+U=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/headroom/0.9.4/jQuery.headroom.min.js" integrity="sha256-ZX/yNShbjqsohH1k95liqY9Gd8uOiE1S4vZc+9KQ1K4=" crossorigin="anonymous"></script><!-- pkgdown --><link href="../pkgdown.css" rel="stylesheet">
<script src="../pkgdown.js"></script><meta property="og:title" content="Spread of a pathogen in a discrete structured population">
<meta property="og:description" content="">
<meta property="og:image" content="/logo.png">
<meta name="twitter:card" content="summary">
<!-- mathjax --><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js" integrity="sha256-nvJJv9wWKEm88qvoQl9ekL2J+k/RWIsaSScxxlsrv8k=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/config/TeX-AMS-MML_HTMLorMML.js" integrity="sha256-84DKXVJXs0/F8OTMzX4UR909+jtl4G7SPypPavF+GfA=" crossorigin="anonymous"></script><!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->
</head>
<body>
    <div class="container template-article">
      <header><div class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <span class="navbar-brand">
        <a class="navbar-link" href="../index.html">nosoi</a>
        <span class="version label label-default" data-toggle="tooltip" data-placement="bottom" title="Released version">1.0.2</span>
      </span>
    </div>

    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
<li>
  <a href="../index.html">
    <span class="fa fa-home fa-lg"></span>
     
  </a>
</li>
<li>
  <a href="../articles/nosoi.html">
    <span class="fas fa fas fa-play-circle"></span>
     
    Getting started
  </a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    <span class="fas fa fas fa-book"></span>
     
    Simulation set up
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
<li>
      <a href="../articles/none.html">Spread of a pathogen in a homogeneous population</a>
    </li>
    <li>
      <a href="../articles/discrete.html">Spread of a pathogen in a discrete structured population</a>
    </li>
    <li>
      <a href="../articles/continuous.html">Spread of a pathogen in a continuous space</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    <span class="fas fa fas fa-file"></span>
     
    Visualise &amp; summarise
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
<li>
      <a href="../articles/output.html">nosoi output</a>
    </li>
    <li>
      <a href="../articles/examples/viz.html">Visualization</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    <span class="fas fa fas fa-file"></span>
     
    Pathogen examples
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
<li>
      <a href="../articles/examples/dengue.html">Spread of dengue virus in a discrete space</a>
    </li>
    <li>
      <a href="../articles/examples/ebola.html">Spread of Ebola-like virus in a continuous space</a>
    </li>
    <li>
      <a href="../articles/examples/vector-competence.html">Epidemiological impact of mosquito vector competence</a>
    </li>
  </ul>
</li>
<li>
  <a href="../reference/index.html">
    <span class="fa fa-file-code-o"></span>
     
    Reference
  </a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Articles
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
<li>
      <a href="../articles/continuous.html">Spread of a pathogen in a continuous space</a>
    </li>
    <li>
      <a href="../articles/discrete.html">Spread of a pathogen in a discrete structured population</a>
    </li>
    <li>
      <a href="../articles/examples/dengue.html">Spread of a dengue-like virus in a discrete space</a>
    </li>
    <li>
      <a href="../articles/examples/ebola.html">Spread of an Ebola-like virus in continuous space</a>
    </li>
    <li>
      <a href="../articles/examples/vector-competence.html">Epidemiological impact of mosquito vector competence variation</a>
    </li>
    <li>
      <a href="../articles/examples/viz.html">Visualization tips</a>
    </li>
    <li>
      <a href="../articles/none.html">Spread of a pathogen in a homogeneous population</a>
    </li>
    <li>
      <a href="../articles/output.html">Output and summarization</a>
    </li>
  </ul>
</li>
      </ul>
<ul class="nav navbar-nav navbar-right">
<li>
  <a href="../news/index.html">Changelog</a>
</li>
<li>
  <a href="https://github.com/slequime/nosoi">
    <span class="fa fa-github fa-lg"></span>
     
  </a>
</li>
      </ul>
</div>
<!--/.nav-collapse -->
  </div>
<!--/.container -->
</div>
<!--/.navbar -->

      

      </header><div class="row">
  <div class="col-md-9 contents">
    <div class="page-header toc-ignore">
      <h1>Spread of a pathogen in a discrete structured population</h1>
                        <h4 class="author">Sebastian Lequime</h4>
            
            <h4 class="date">2020-04-03</h4>
      
      <small class="dont-index">Source: <a href="https://github.com/slequime/nosoi/blob/master/vignettes/discrete.Rmd"><code>vignettes/discrete.Rmd</code></a></small>
      <div class="hidden name"><code>discrete.Rmd</code></div>

    </div>

    
    
<p>Aside from the simple simulation set up, explored in <a href="none.html">another tutorial</a>, where hosts are “not structured”, <code>nosoi</code> can take into account a population structured either in discrete states or in a continuous space. We focus here on a discrete state structure (for the continuous structure, see <a href="continuous.html">this tutorial</a>).</p>
<p>The discrete structure is intended to allow the simulation to take place in a geographical context with discrete states such as countries, regions, islands, cities. Note that other kind of structures could be taken into account (e.g. high risk/low risk, etc). In this setting, parameter values are allowed to change according to the host’s current location among the available states.</p>
<p>This tutorial focuses on setting up a <code>nosoi</code> simulation for a pathogen which host population is structured between different locations.</p>
<div id="structure-of-the-population" class="section level1">
<h1 class="hasAnchor">
<a href="#structure-of-the-population" class="anchor"></a>Structure of the population</h1>
<p>We consider here a population of hosts that are in three different locations called “A”, “B” and “C”. Hosts can move (if they undergo a movement event) between these locations with a certain probability that can be set directly, or derived from other data. Here, we take the transition matrix, called here after <code>structure.matrix</code>, to be:</p>
<pre><code>#&gt;     A   B   C
#&gt; A 0.0 0.5 0.5
#&gt; B 0.2 0.0 0.8
#&gt; C 0.4 0.6 0.0</code></pre>
<p>It can graphically be represented as follow:</p>
<p><img src="discrete_files/figure-html/setupMatrix-1.png" width="700"></p>
<p>For <code>structure.matrix</code> to be adequate, a few rules have to be followed:</p>
<ul>
<li>
<code>structure.matrix</code> should be of class <code>matrix</code>;</li>
<li>
<code>structure.matrix</code> should have the same number of rows and columns, and they should have the same names;</li>
<li>
<code>structure.matrix</code> rows represent departure states and columns arrival states. Each coefficient is the probability of moving from a departure state to a different arrival state if a movement is made. Row values thus sum up to 1.</li>
</ul>
</div>
<div id="setting-up-the-simulation" class="section level1">
<h1 class="hasAnchor">
<a href="#setting-up-the-simulation" class="anchor"></a>Setting up the simulation</h1>
<p>The wrapper function <code>nosoiSim</code> takes all the arguments that will be passed down to the simulator, in the case of this tutorial <code>singleDiscrete</code> (for “single host, discrete structure”). We thus start by providing the options <code>type="single"</code> and <code>popStructure="discrete"</code> to set up the analysis:</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb2-1" data-line-number="1">SimulationSingle &lt;-<span class="st"> </span><span class="kw"><a href="../reference/nosoiSim.html">nosoiSim</a></span>(<span class="dt">type=</span><span class="st">"single"</span>, <span class="dt">popStructure=</span><span class="st">"discrete"</span>, ...)</a></code></pre></div>
<p>This simulation type requires several arguments or options in order to run, namely:</p>
<ul>
<li><code>length.sim</code></li>
<li><code>max.infected</code></li>
<li><code>init.individuals</code></li>
<li><code>init.structure</code></li>
<li><code>structure.matrix</code></li>
<li>
<code>pExit</code> with <code>param.pExit</code>, <code>timeDep.pExit</code>, <code>diff.pExit</code> and <code>hostCount.pExit</code>
</li>
<li>
<code>pMove</code> with <code>param.pMove</code>, <code>timeDep.pMove</code>, <code>diff.pMove</code> and <code>hostCount.pMove</code>
</li>
<li>
<code>nContact</code> with <code>param.nContact</code>, <code>timeDep.nContact</code>, <code>diff.nContact</code> and <code>hostCount.nContact</code>
</li>
<li>
<code>pTrans</code> with <code>param.pTrans</code>, <code>timeDep.pTrans</code>, <code>diff.pTrans</code> and <code>hostCount.pTrans</code>
</li>
<li><code>prefix.host.A</code></li>
<li><code>print.progress</code></li>
<li><code>print.step</code></li>
</ul>
<p>All the <code>param.*</code> elements provide individual-level parameters to be taken into account, while the <code>timeDep.*</code> elements inform the simulator if the “absolute” simulation time should be taken into account. The <code>diff.*</code> elements inform the simulator if there is a differential probability according to the state the host is currently in and the <code>hostCount.*</code> elements inform the simulator if the number of host in each state has to be taken into account. All parameters must be provided, although <code>timeDep.*</code>, <code>diff.*</code> and <code>hostCount.*</code> have default values set to <code>FALSE</code>; if you do not want to use these options, then you do not have to explicitly provide a value.</p>
<div id="general-parameters" class="section level2">
<h2 class="hasAnchor">
<a href="#general-parameters" class="anchor"></a>General parameters</h2>
<p><code>length.sim</code> and <code>max.infected</code> are general parameters that define the simulation:</p>
<ul>
<li>
<code>length.sim</code> is the maximum number of time units (e.g. days, months, years, or another time unit of choice) during which the simulation will be run.</li>
<li>
<code>max.infected</code> is the maximum number of individuals that can be infected during the simulation.</li>
</ul>
<p><code>init.individuals</code> and <code>init.structure</code> are the “seeding parameters”:</p>
<ul>
<li>
<code>init.individuals</code> defines the number of individuals (an integer above 1) that will start a transmission chain. Keep in mind that you will have as many transmission chains as initial individuals, which is equivalent as launching a number of independent nosoi simulations.</li>
<li>
<code>init.structure</code> specifies the original location of these individuals in the structured population (has to be the same original location for all starting individuals). The location provided in <code>init.structure</code> should of course be present in the <code>structure.matrix</code>.</li>
</ul>
<p>Here, we will run a simulation starting with 1 individual, for a maximum of 1,000 infected individuals and a maximum time of 300 days.</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb3-1" data-line-number="1">SimulationSingle &lt;-<span class="st"> </span><span class="kw"><a href="../reference/nosoiSim.html">nosoiSim</a></span>(<span class="dt">type=</span><span class="st">"single"</span>, <span class="dt">popStructure=</span><span class="st">"none"</span>,</a>
<a class="sourceLine" id="cb3-2" data-line-number="2">                             <span class="dt">length.sim=</span><span class="dv">300</span>, <span class="dt">max.infected=</span><span class="dv">1000</span>, <span class="dt">init.individuals=</span><span class="dv">1</span>, ...)</a></code></pre></div>
</div>
<div id="core-functions" class="section level2">
<h2 class="hasAnchor">
<a href="#core-functions" class="anchor"></a>Core functions</h2>
<p>The core functions <code>pExit</code>, <code>nContact</code>, <code>pMove</code> and <code>pTrans</code> each follow the <a href="nosoi.html#setting-up-the-core-functions">same principles to be set up</a>.</p>
<p>To accommodate for different scenarios, they can be constant, time-dependent (using the relative time since infection <code>t</code> for each individual or the “absolute” time <code>pres.time</code> of the simulation) or even individually parameterized, to include some stochasticity at the individual-host level.</p>
<p>In any case, the provided function, like all other core functions in <code>nosoi</code>, has to be expressed as a function of time <code>t</code>, even if time is not used to compute the probability.</p>
<p>In case the function uses individual-based parameters, they must be specified in a list of functions (called <code>param.pExit</code>, <code>param.nContact</code>, <code>param.pMove</code> or <code>param.pTrans</code>) (see <a href="nosoi.html#parameters">Get started</a>). If no individual-based parameters are used, then these lists are set to <code>NA</code>.</p>
<blockquote>
<p>Keep in mind that <code>pExit</code>, <code>pMove</code>, and <code>pTrans</code> have to return a probability (i.e. a value between 0 and 1) while <code>nContact</code> should return a natural number (positive integer or zero).</p>
</blockquote>
<p>Several parameters, such as the time since infection, the “absolute” time of the simulation, the location (in the discrete states) and individual-based parameters can be combined within the same function.</p>
<blockquote>
<p><code>nosoi</code> can be flexible in what it allows as parameters in your function, but a common general structure should be observed. The argument of the function should be (in that order):</p>
<ol style="list-style-type: decimal">
<li>time since infection <code>t</code> (compulsory);</li>
<li>“absolute” time <code>prestime</code> (optional);</li>
<li>current state <code>current.in</code> (optional);</li>
<li>host count in state <code>host.count</code> (optional);</li>
<li>other individual-based parameter(s), provided in <code>param.function</code>.</li>
</ol>
<p>If one of the argument is not used (except <code>t</code>), then you do not have to provide it and can continue with the next argument.</p>
</blockquote>
<div id="pexit-param-pexit-timedep-pexit-diff-pexit-and-hostcount-pexit" class="section level3">
<h3 class="hasAnchor">
<a href="#pexit-param-pexit-timedep-pexit-diff-pexit-and-hostcount-pexit" class="anchor"></a><code>pExit</code>, <code>param.pExit</code>, <code>timeDep.pExit</code>, <code>diff.pExit</code> and <code>hostCount.pExit</code>
</h3>
<ul>
<li>
<code>pExit</code> is the first required fundamental parameter and provides a daily probability for a host to leave the simulation (either cured, died, etc.).</li>
<li>
<code>param.pExit</code> is the list of functions needed to individually parameterize <code>pExit</code> (see <a href="nosoi.html#parameters">Get started</a>). The name of each function in the list has to match the name of the parameter it is sampling for <code>pExit</code>.</li>
<li>
<code>timeDep.pExit</code> allows for <code>pExit</code> to be dependent on the “absolute” time of the simulation, to account - for example - for seasonality or other external time-related covariates. By default, <code>timeDep.pExit</code> is set to <code>FALSE</code>.</li>
<li>
<code>diff.pExit</code> allows <code>pExit</code> to differ according to the current discrete state of the host. This can be useful, for example, if one state has a higher mortality rate (or better cures!) for the infection, in that case the probability to exit the simulation is higher. By default, <code>diff.pExit</code> is set to <code>FALSE</code>. Be careful, every state should give back a result for <code>pExit</code>.</li>
<li>
<code>hostCount.pExit</code> allows <code>pExit</code> to differ according to the number of hosts currently in a state. By default, <code>hostCount.pExit</code> is set to <code>FALSE</code>. To use <code>hostCount.pExit</code>, <code>diff.pExit</code> has to be set to <code>TRUE</code> too.</li>
</ul>
</div>
<div id="pmove-param-pmove-timedep-pmove-diff-pmove-and-hostcount-pmove" class="section level3">
<h3 class="hasAnchor">
<a href="#pmove-param-pmove-timedep-pmove-diff-pmove-and-hostcount-pmove" class="anchor"></a><code>pMove</code>, <code>param.pMove</code>, <code>timeDep.pMove</code>, <code>diff.pMove</code> and <code>hostCount.pMove</code>
</h3>
<ul>
<li>
<code>pMove</code> is the probability (per unit of time) for a host to do move, i.e. to leave its current state (for example, leaving state “A”). It should not be confused with the probabilities extracted from the <code>structure.matrix</code>, which represent the probability to go to a specific location once a movement is ongoing (for example, going to “B” or “C” while coming from “A”).</li>
<li>
<code>param.pMove</code> is the list of functions needed to individually parameterize <code>pMove</code> (see <a href="nosoi.html#parameters">Get started</a>). The name of each function in the list has to match the name of the parameter it is sampling for <code>pMove</code>.</li>
<li>
<code>timeDep.pMove</code> allows for <code>pMove</code> to be dependent of the “absolute” time of the simulation, to account, for example, for seasonality or other external time related covariates. By default, <code>timeDep.pMove</code> is set to <code>FALSE</code>.</li>
<li>
<code>diff.pMove</code> allows <code>pMove</code> to be different according to the current discrete state of the host, to account, for example, of different traveling rates in different states. By default, <code>diff.pMove</code> is set to <code>FALSE</code>. Be careful, every state should give back a result for <code>pMove</code>.</li>
<li>
<code>hostCount.pMove</code> allows for <code>pMove</code> to differ according to the number of hosts currently in a state. By default, <code>hostCount.pMove</code> is set to <code>FALSE</code>. To use <code>hostCount.pMove</code>, <code>diff.pMove</code> has to be set to <code>TRUE</code> too.</li>
</ul>
</div>
<div id="ncontact-param-ncontact-timedep-ncontact-diff-ncontact-and-hostcount-ncontact" class="section level3">
<h3 class="hasAnchor">
<a href="#ncontact-param-ncontact-timedep-ncontact-diff-ncontact-and-hostcount-ncontact" class="anchor"></a><code>nContact</code>, <code>param.nContact</code>, <code>timeDep.nContact</code>, <code>diff.nContact</code> and <code>hostCount.nContact</code>
</h3>
<ul>
<li>
<code>nContact</code> represents the number (expressed as a positive integer) of potentially infectious contacts an infected hosts can encounter per unit of time. At each time point, a number of contacts will be determined for each active host in the simulation. The number of contacts (i.e. the output of your function) has to be an integer and can be set to zero.</li>
<li>
<code>param.nContact</code> is the list of functions needed to individually parameterize <code>nContact</code> (see <a href="nosoi.html#parameters">Get started</a>). The name of each function in the list has to match the name of the parameter it is sampling for <code>nContact</code>.</li>
<li>
<code>timeDep.nContact</code> allows for <code>nContact</code> to be dependent on the “absolute” time of the simulation, to account - for example - for seasonality or other external time-related covariates. By default, <code>timeDep.nContact</code> is set to <code>FALSE</code>.</li>
<li>
<code>diff.nContact</code> allows for <code>nContact</code> to differ according to the current discrete state of the host. By default, <code>diff.nContact</code> is set to <code>FALSE</code>. Be careful, every state should give back a result for <code>nContact</code>.</li>
<li>
<code>hostCount.nContact</code> allows for <code>nContact</code> to differ according to the number of hosts currently in a state. This can be useful to adjust the number of contact to the number of potentially susceptible hosts if the infected population is close to the maximum size of the population in a state. By default, <code>hostCount.nContact</code> is set to <code>FALSE</code>. To use <code>hostCount.nContact</code>, <code>diff.nContact</code> has to be set to <code>TRUE</code> too.</li>
</ul>
</div>
<div id="ptrans-param-ptrans-timedep-ptransdiff-ptrans-and-hostcount-ptrans" class="section level3">
<h3 class="hasAnchor">
<a href="#ptrans-param-ptrans-timedep-ptransdiff-ptrans-and-hostcount-ptrans" class="anchor"></a><code>pTrans</code>, <code>param.pTrans</code>, <code>timeDep.pTrans</code>,<code>diff.pTrans</code> and <code>hostCount.pTrans</code>
</h3>
<ul>
<li>
<code>pTrans</code> is the heart of the transmission process and represents the probability of transmission over time (when a contact occurs).</li>
<li>
<code>param.pTrans</code> is the list of functions needed to individually parameterize <code>pTrans</code> (see <a href="nosoi.html#parameters">Get started</a>). The name of each function in the list has to match the name of the parameter it is sampling for <code>pTrans</code>.</li>
<li>
<code>timeDep.pTrans</code> allows for <code>pTrans</code> to be dependent on the “absolute” time of the simulation, to account - for example - for seasonality or other external time-related covariates. By default, <code>timeDep.pTrans</code> is set to <code>FALSE</code>.</li>
<li>
<code>diff.pTrans</code> allows for <code>pTrans</code> to be different according to the current discrete state of the host. This can be used to account of different dynamics linked to external factors common within a state, such as temperature for example. By default, <code>diff.pTrans</code> is set to <code>FALSE</code>. Be careful, every state should give back a result for <code>pTrans</code>.</li>
<li>
<code>hostCount.pTrans</code> allows <code>pTrans</code> to differ according to the number of hosts currently in a state. By default, <code>hostCount.pTrans</code> is set to <code>FALSE</code>. To use <code>hostCount.pTrans</code>, <code>diff.pTrans</code> has to be set to <code>TRUE</code> too.</li>
</ul>
</div>
</div>
<div id="miscellaneous" class="section level2">
<h2 class="hasAnchor">
<a href="#miscellaneous" class="anchor"></a>Miscellaneous</h2>
<p><code>prefix.host</code> allows you to define the first character(s) for the hosts’ unique ID. It will be followed by a hyphen and a unique number. By default, <code>prefix.host</code> is “H” for “Host”.</p>
<p><code>print.progress</code> allows you to have some information printed on the screen about the simulation as it is running. It will print something every <code>print.step</code>. By default, <code>print.progress</code> is activated with a <code>print.step = 10</code> (you can change this frequency), but you may want to deactivate it by setting <code>print.progress=FALSE</code>.</p>
</div>
<div id="dual-host" class="section level2">
<h2 class="hasAnchor">
<a href="#dual-host" class="anchor"></a>Dual host</h2>
<p>In the case of a dual host simulation, several parameters of the <code>nosoiSim</code> will have to be specified for each host type, designated by <code>A</code> and <code>B</code>. The wrapper function <code>nosoiSim</code> will then take all the arguments that will be passed down to the simulator, in the case of this tutorial <code>dualDiscrete</code> (for “dual host, discrete structure”). We thus start by providing the options <code>type="dual"</code> and <code>popStructure="discrete"</code> to set up the analysis:</p>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb4-1" data-line-number="1">SimulationDual &lt;-<span class="st"> </span><span class="kw"><a href="../reference/nosoiSim.html">nosoiSim</a></span>(<span class="dt">type=</span><span class="st">"dual"</span>, <span class="dt">popStructure=</span><span class="st">"discrete"</span>, ...)</a></code></pre></div>
<p>This function takes several arguments or options to be able to run, namely:</p>
<ul>
<li><code>length.sim</code></li>
<li><code>max.infected.A</code></li>
<li><code>max.infected.B</code></li>
<li><code>init.individuals.A</code></li>
<li><code>init.individuals.B</code></li>
<li><code>init.structure.A</code></li>
<li><code>init.structure.B</code></li>
<li><code>structure.matrix.A</code></li>
<li><code>structure.matrix.B</code></li>
<li>
<code>pExit.A</code> with <code>param.pExit.A</code>, <code>timeDep.pExit.A</code>, <code>diff.pExit.A</code> and <code>hostCount.pExit.A</code>
</li>
<li>
<code>pMove.A</code> with <code>param.pMove.A</code>, <code>timeDep.pMove.A</code>, <code>diff.pMove.A</code> and <code>hostCount.pMove.A</code>
</li>
<li>
<code>nContact.A</code> with <code>param.nContact.A</code>, <code>timeDep.nContact.A</code>, <code>diff.nContact.A</code> and <code>hostCount.nContact.A</code>
</li>
<li>
<code>pTrans.A</code> with <code>param.pTrans.A</code>, <code>timeDep.pTrans.A</code>, <code>diff.pTrans.A</code> and <code>hostCount.pTrans.A</code>
</li>
<li><code>prefix.host.A</code></li>
<li>
<code>pExit.B</code> with <code>param.pExit.B</code>, <code>timeDep.pExit.B</code>, <code>diff.pExit.B</code> and <code>hostCount.pExit.B</code>
</li>
<li>
<code>pMove.B</code> with <code>param.pMove.B</code>, <code>timeDep.pMove.B</code>, <code>diff.pMove.B</code> and <code>hostCount.pMove.B</code>
</li>
<li>
<code>nContact.B</code> with <code>param.nContact.B</code>, <code>timeDep.nContact.B</code>, <code>diff.nContact.B</code> and <code>hostCount.nContact.B</code>
</li>
<li>
<code>pTrans.B</code> with <code>param.pTrans.B</code>, <code>timeDep.pTrans.B</code>, <code>diff.pTrans.B</code> and <code>hostCount.pTrans.B</code>
</li>
<li><code>prefix.host.B</code></li>
<li><code>print.progress</code></li>
<li><code>print.step</code></li>
</ul>
<p>As you can see, host-type dependent parameters are now designated by the suffix <code>.A</code> or <code>.B</code>.</p>
<p>Both <code>max.infected.A</code> and <code>max.infected.B</code> have to be provided in order to set an upper limit on the simulation size. To initiate the simulation, you have to provide at least one starting host, either <code>A</code> or <code>B</code> in <code>init.individuals.A</code> or <code>init.individuals.B</code> respectively, as well as a starting position in <code>init.individuals.A</code> or <code>init.individuals.B</code>, respectively. If you want to start the simulation with one host only, then <code>init.individuals</code> of the other can be set to 0 and <code>init.structure</code> to <code>NA</code>.</p>
<p>A major difference here is that hosts may or may not share the same <code>structure.matrix</code>. However, since they exist in the same “world”, they should share the same state names. It is also possible to have a host that does not move. In such case, <code>pMove</code> can be set to <code>NA</code>. In such a “non-movement” case, a transition matrix with all the state names should still be provided.</p>
<p>Here again, all parameters must be provided for both hosts, although <code>timeDep</code>, <code>diff</code> and <code>hostCount</code> have default values set to <code>FALSE</code>; if you do not want to use these options, then you do not have to explicitly provide a value. Be careful to switch <code>diff</code> to <code>TRUE</code> if you want to use <code>hostCount</code>, and remember to provide a result for each state.</p>
</div>
</div>
<div id="running-nosoi" class="section level1">
<h1 class="hasAnchor">
<a href="#running-nosoi" class="anchor"></a>Running <code>nosoi</code>
</h1>
<div id="single-host" class="section level2">
<h2 class="hasAnchor">
<a href="#single-host" class="anchor"></a>Single host</h2>
<p>We present here a very simple simulation for a single host pathogen.</p>
<div id="pexit" class="section level3">
<h3 class="hasAnchor">
<a href="#pexit" class="anchor"></a>pExit</h3>
<p>For <code>pExit</code>, we choose a probability that depends on the location where the host currently resides. Each location (state) has to be present, as shown in this example:</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb5-1" data-line-number="1">p_Exit_fct  &lt;-<span class="st"> </span><span class="cf">function</span>(t,current.in){</a>
<a class="sourceLine" id="cb5-2" data-line-number="2">  <span class="cf">if</span>(current.in<span class="op">==</span><span class="st">"A"</span>){<span class="kw"><a href="https://rdrr.io/r/base/function.html">return</a></span>(<span class="fl">0.02</span>)}</a>
<a class="sourceLine" id="cb5-3" data-line-number="3">  <span class="cf">if</span>(current.in<span class="op">==</span><span class="st">"B"</span>){<span class="kw"><a href="https://rdrr.io/r/base/function.html">return</a></span>(<span class="fl">0.05</span>)}</a>
<a class="sourceLine" id="cb5-4" data-line-number="4">  <span class="cf">if</span>(current.in<span class="op">==</span><span class="st">"C"</span>){<span class="kw"><a href="https://rdrr.io/r/base/function.html">return</a></span>(<span class="fl">0.1</span>)}}</a>
<a class="sourceLine" id="cb5-5" data-line-number="5"><span class="er">}</span></a></code></pre></div>
<p>This function indicates that if the host is in state “A”, it has 2% chance to exit, 5% if in state “B” and 10% if in state “C”. Remember that <code>pExit</code>, like the other core functions, has to be function of <code>t</code>, even if <code>t</code> is not used. Since <code>pExit</code> is dependent on the location, <code>diff.pExit=TRUE</code>. However, there is no use of the “absolute” time of the simulation nor individual-based parameters, hence <code>timeDep.pExit=FALSE</code> and <code>param.pExit=NA</code>.</p>
</div>
<div id="pmove" class="section level3">
<h3 class="hasAnchor">
<a href="#pmove" class="anchor"></a>pMove</h3>
<p>We choose a constant value for <code>pMove</code>, namely 0.1, i.e. an infected host has 10% chance to leave its state (here a location) for each unit of time.</p>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb6-1" data-line-number="1">p_Move_fct  &lt;-<span class="st"> </span><span class="cf">function</span>(t){<span class="kw"><a href="https://rdrr.io/r/base/function.html">return</a></span>(<span class="fl">0.1</span>)}</a></code></pre></div>
<p>Remember that <code>pMove</code>, like the other core functions, has to be a function of <code>t</code>, even if <code>t</code> is not used. Since <code>pMove</code> is not dependent on the location, <code>diff.pMove=FALSE</code>. Similarly, there is no use of the “absolute” time of the simulation nor individual-based parameters, hence <code>timeDep.pMove=FALSE</code> and <code>param.pMove=NA</code>.</p>
</div>
<div id="ncontact" class="section level3">
<h3 class="hasAnchor">
<a href="#ncontact" class="anchor"></a>nContact</h3>
<p>For <code>nContact</code>, we choose a constant function that will draw a value in a normal distribution of <em>mean</em> 0.5 and <em>sd</em> 1, round it, and take its absolute value.</p>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb7-1" data-line-number="1">n_contact_fct =<span class="st"> </span><span class="cf">function</span>(t){<span class="kw"><a href="https://rdrr.io/r/base/MathFun.html">abs</a></span>(<span class="kw"><a href="https://rdrr.io/r/base/Round.html">round</a></span>(<span class="kw"><a href="https://rdrr.io/r/stats/Normal.html">rnorm</a></span>(<span class="dv">1</span>, <span class="fl">0.5</span>, <span class="dv">1</span>), <span class="dv">0</span>))}</a></code></pre></div>
<p>The distribution of <code>nContact</code> looks as follows:</p>
<p><img src="discrete_files/figure-html/nContact2-1.png" width="700"></p>
<p>At each time and for each infected host, <code>nContact</code> will be drawn anew. Remember that <code>nContact</code>, like the other core functions has to be function of <code>t</code>, even if <code>t</code> is not used. Since <code>nContact</code> is constant here, there is no use of the “absolute” time of the simulation, the location of the host, nor individual-based parameters. So <code>param.nContact=NA</code>, <code>timeDep.nContact=FALSE</code> and <code>diff.nContact=FALSE</code>.</p>
</div>
<div id="ptrans" class="section level3">
<h3 class="hasAnchor">
<a href="#ptrans" class="anchor"></a>pTrans</h3>
<p>We choose <code>pTrans</code> in the form of a threshold function: before a certain amount of time since initial infection, the host does not transmit (incubation time, which we call <code>t_incub</code>), and after that time, it will transmit with a certain (constant) probability (which we call <code>p_max</code>). This function is dependent of the time since the host’s infection <code>t</code>.</p>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb8-1" data-line-number="1">p_Trans_fct &lt;-<span class="st"> </span><span class="cf">function</span>(t, p_max, t_incub){</a>
<a class="sourceLine" id="cb8-2" data-line-number="2">    <span class="cf">if</span>(t <span class="op">&lt;</span><span class="st"> </span>t_incub){p=<span class="dv">0</span>}</a>
<a class="sourceLine" id="cb8-3" data-line-number="3">    <span class="cf">if</span>(t <span class="op">&gt;=</span><span class="st"> </span>t_incub){p=p_max}</a>
<a class="sourceLine" id="cb8-4" data-line-number="4">    <span class="kw"><a href="https://rdrr.io/r/base/function.html">return</a></span>(p)</a>
<a class="sourceLine" id="cb8-5" data-line-number="5">}</a></code></pre></div>
<p>Because each host is different (slightly different biotic and abiotic factors), you can expect each host to exhibit differences in the dynamics of infection, and hence the probability of transmission over time. Thus, <code>t_incub</code> and <code>p_max</code> will be sampled for each host individually according to a certain distribution. <code>t_incub</code> will be sampled from a normal distribution of <span class="math inline">\(mean\)</span> = 7 and <span class="math inline">\(sd\)</span> = 1, while <code>p_max</code> will be sampled from a beta distribution with shape parameters <span class="math inline">\(\alpha\)</span> = 5 and <span class="math inline">\(\beta\)</span> = 2:</p>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb9-1" data-line-number="1">t_incub_fct &lt;-<span class="st"> </span><span class="cf">function</span>(x){<span class="kw"><a href="https://rdrr.io/r/stats/Normal.html">rnorm</a></span>(x, <span class="dt">mean=</span><span class="dv">7</span>, <span class="dt">sd=</span><span class="dv">1</span>)}</a>
<a class="sourceLine" id="cb9-2" data-line-number="2">p_max_fct &lt;-<span class="st"> </span><span class="cf">function</span>(x){<span class="kw"><a href="https://rdrr.io/r/stats/Beta.html">rbeta</a></span>(x, <span class="dt">shape1=</span><span class="dv">5</span>, <span class="dt">shape2=</span><span class="dv">2</span>)}</a></code></pre></div>
<p>Note that here <code>t_incub</code> and <code>p_max</code> are functions of <code>x</code> and not <code>t</code> (they are not core functions but individual-based parameters), and <code>x</code> enters the function as the number of draws to make.</p>
<p>Taken together, the profile for <code>pTrans</code> for a subset of 200 individuals in the population will look as follows:</p>
<p><img src="discrete_files/figure-html/pTrans3-1.png" width="700"></p>
<p><code>pTrans</code> is not dependent of the “absolute” time of the simulation nor it is dependent of the hosts location, hence <code>timeDep.pTrans=FALSE</code> and <code>diff.pTrans=FALSE</code>. However, since we make use of individual-based parameters, we have to provide a <code>param.pTrans</code> as a list of functions. The name of each element within this list should have the same name that the core function (here <code>pTrans</code>) uses as argument, e.g.:</p>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb10-1" data-line-number="1">t_incub_fct &lt;-<span class="st"> </span><span class="cf">function</span>(x){<span class="kw"><a href="https://rdrr.io/r/stats/Normal.html">rnorm</a></span>(x,<span class="dt">mean =</span> <span class="dv">7</span>,<span class="dt">sd=</span><span class="dv">1</span>)}</a>
<a class="sourceLine" id="cb10-2" data-line-number="2">p_max_fct &lt;-<span class="st"> </span><span class="cf">function</span>(x){<span class="kw"><a href="https://rdrr.io/r/stats/Beta.html">rbeta</a></span>(x,<span class="dt">shape1 =</span> <span class="dv">5</span>,<span class="dt">shape2=</span><span class="dv">2</span>)}</a>
<a class="sourceLine" id="cb10-3" data-line-number="3"></a>
<a class="sourceLine" id="cb10-4" data-line-number="4">param_pTrans =<span class="st"> </span><span class="kw"><a href="https://rdrr.io/r/base/list.html">list</a></span>(<span class="dt">p_max=</span>p_max_fct,<span class="dt">t_incub=</span>t_incub_fct)</a></code></pre></div>
</div>
<div id="running" class="section level3">
<h3 class="hasAnchor">
<a href="#running" class="anchor"></a>Running</h3>
<p>Once <code>nosoiSim</code> is set up, you can run the simulation (here the “seed” ensures that you will get the same results as in this tutorial).</p>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb11-1" data-line-number="1"><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span>(nosoi)</a>
<a class="sourceLine" id="cb11-2" data-line-number="2"><span class="co">#&gt; Loading required package: data.table</span></a>
<a class="sourceLine" id="cb11-3" data-line-number="3"><span class="co">#&gt; </span></a>
<a class="sourceLine" id="cb11-4" data-line-number="4"><span class="co">#&gt; Attaching package: 'data.table'</span></a>
<a class="sourceLine" id="cb11-5" data-line-number="5"><span class="co">#&gt; The following objects are masked from 'package:dplyr':</span></a>
<a class="sourceLine" id="cb11-6" data-line-number="6"><span class="co">#&gt; </span></a>
<a class="sourceLine" id="cb11-7" data-line-number="7"><span class="co">#&gt;     between, first, last</span></a>
<a class="sourceLine" id="cb11-8" data-line-number="8"></a>
<a class="sourceLine" id="cb11-9" data-line-number="9"><span class="co">#Transition matrix</span></a>
<a class="sourceLine" id="cb11-10" data-line-number="10">transition.matrix &lt;-<span class="st"> </span><span class="kw"><a href="https://rdrr.io/r/base/matrix.html">matrix</a></span>(<span class="kw"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="dv">0</span>,<span class="fl">0.2</span>,<span class="fl">0.4</span>,<span class="fl">0.5</span>,<span class="dv">0</span>,<span class="fl">0.6</span>,<span class="fl">0.5</span>,<span class="fl">0.8</span>,<span class="dv">0</span>),<span class="dt">nrow =</span> <span class="dv">3</span>, <span class="dt">ncol =</span> <span class="dv">3</span>,<span class="dt">dimnames=</span><span class="kw"><a href="https://rdrr.io/r/base/list.html">list</a></span>(<span class="kw"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="st">"A"</span>,<span class="st">"B"</span>,<span class="st">"C"</span>),<span class="kw"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="st">"A"</span>,<span class="st">"B"</span>,<span class="st">"C"</span>)))</a>
<a class="sourceLine" id="cb11-11" data-line-number="11"></a>
<a class="sourceLine" id="cb11-12" data-line-number="12"><span class="co">#pExit</span></a>
<a class="sourceLine" id="cb11-13" data-line-number="13">p_Exit_fct  &lt;-<span class="st"> </span><span class="cf">function</span>(t,current.in){</a>
<a class="sourceLine" id="cb11-14" data-line-number="14">  <span class="cf">if</span>(current.in<span class="op">==</span><span class="st">"A"</span>){<span class="kw"><a href="https://rdrr.io/r/base/function.html">return</a></span>(<span class="fl">0.02</span>)}</a>
<a class="sourceLine" id="cb11-15" data-line-number="15">  <span class="cf">if</span>(current.in<span class="op">==</span><span class="st">"B"</span>){<span class="kw"><a href="https://rdrr.io/r/base/function.html">return</a></span>(<span class="fl">0.05</span>)}</a>
<a class="sourceLine" id="cb11-16" data-line-number="16">  <span class="cf">if</span>(current.in<span class="op">==</span><span class="st">"C"</span>){<span class="kw"><a href="https://rdrr.io/r/base/function.html">return</a></span>(<span class="fl">0.1</span>)}</a>
<a class="sourceLine" id="cb11-17" data-line-number="17">}</a>
<a class="sourceLine" id="cb11-18" data-line-number="18"></a>
<a class="sourceLine" id="cb11-19" data-line-number="19"><span class="co">#pMove</span></a>
<a class="sourceLine" id="cb11-20" data-line-number="20">p_Move_fct  &lt;-<span class="st"> </span><span class="cf">function</span>(t){<span class="kw"><a href="https://rdrr.io/r/base/function.html">return</a></span>(<span class="fl">0.1</span>)}</a>
<a class="sourceLine" id="cb11-21" data-line-number="21"></a>
<a class="sourceLine" id="cb11-22" data-line-number="22"><span class="co">#nContact</span></a>
<a class="sourceLine" id="cb11-23" data-line-number="23">n_contact_fct =<span class="st"> </span><span class="cf">function</span>(t){<span class="kw"><a href="https://rdrr.io/r/base/MathFun.html">abs</a></span>(<span class="kw"><a href="https://rdrr.io/r/base/Round.html">round</a></span>(<span class="kw"><a href="https://rdrr.io/r/stats/Normal.html">rnorm</a></span>(<span class="dv">1</span>, <span class="fl">0.5</span>, <span class="dv">1</span>), <span class="dv">0</span>))}</a>
<a class="sourceLine" id="cb11-24" data-line-number="24"></a>
<a class="sourceLine" id="cb11-25" data-line-number="25"><span class="co">#pTrans</span></a>
<a class="sourceLine" id="cb11-26" data-line-number="26">proba &lt;-<span class="st"> </span><span class="cf">function</span>(t,p_max,t_incub){</a>
<a class="sourceLine" id="cb11-27" data-line-number="27">  <span class="cf">if</span>(t <span class="op">&lt;=</span><span class="st"> </span>t_incub){p=<span class="dv">0</span>}</a>
<a class="sourceLine" id="cb11-28" data-line-number="28">  <span class="cf">if</span>(t <span class="op">&gt;=</span><span class="st"> </span>t_incub){p=p_max}</a>
<a class="sourceLine" id="cb11-29" data-line-number="29">  <span class="kw"><a href="https://rdrr.io/r/base/function.html">return</a></span>(p)</a>
<a class="sourceLine" id="cb11-30" data-line-number="30">}</a>
<a class="sourceLine" id="cb11-31" data-line-number="31"></a>
<a class="sourceLine" id="cb11-32" data-line-number="32">t_incub_fct &lt;-<span class="st"> </span><span class="cf">function</span>(x){<span class="kw"><a href="https://rdrr.io/r/stats/Normal.html">rnorm</a></span>(x,<span class="dt">mean =</span> <span class="dv">5</span>,<span class="dt">sd=</span><span class="dv">1</span>)}</a>
<a class="sourceLine" id="cb11-33" data-line-number="33">p_max_fct &lt;-<span class="st"> </span><span class="cf">function</span>(x){<span class="kw"><a href="https://rdrr.io/r/stats/Beta.html">rbeta</a></span>(x,<span class="dt">shape1 =</span> <span class="dv">5</span>,<span class="dt">shape2=</span><span class="dv">2</span>)}</a>
<a class="sourceLine" id="cb11-34" data-line-number="34"></a>
<a class="sourceLine" id="cb11-35" data-line-number="35">param_pTrans =<span class="st"> </span><span class="kw"><a href="https://rdrr.io/r/base/list.html">list</a></span>(<span class="dt">p_max=</span>p_max_fct,<span class="dt">t_incub=</span>t_incub_fct)</a>
<a class="sourceLine" id="cb11-36" data-line-number="36"></a>
<a class="sourceLine" id="cb11-37" data-line-number="37"><span class="co"># Starting the simulation ------------------------------------</span></a>
<a class="sourceLine" id="cb11-38" data-line-number="38"></a>
<a class="sourceLine" id="cb11-39" data-line-number="39"><span class="kw"><a href="https://rdrr.io/r/base/Random.html">set.seed</a></span>(<span class="dv">846</span>)</a>
<a class="sourceLine" id="cb11-40" data-line-number="40">SimulationSingle &lt;-<span class="st"> </span><span class="kw"><a href="../reference/nosoiSim.html">nosoiSim</a></span>(<span class="dt">type=</span><span class="st">"single"</span>, <span class="dt">popStructure=</span><span class="st">"discrete"</span>,</a>
<a class="sourceLine" id="cb11-41" data-line-number="41">                             <span class="dt">length.sim=</span><span class="dv">300</span>, <span class="dt">max.infected=</span><span class="dv">300</span>, <span class="dt">init.individuals=</span><span class="dv">1</span>, <span class="dt">init.structure=</span><span class="st">"A"</span>, </a>
<a class="sourceLine" id="cb11-42" data-line-number="42">                             </a>
<a class="sourceLine" id="cb11-43" data-line-number="43">                             <span class="dt">structure.matrix=</span>transition.matrix,</a>
<a class="sourceLine" id="cb11-44" data-line-number="44">                             </a>
<a class="sourceLine" id="cb11-45" data-line-number="45">                             <span class="dt">pExit =</span> p_Exit_fct,</a>
<a class="sourceLine" id="cb11-46" data-line-number="46">                             <span class="dt">param.pExit=</span><span class="ot">NA</span>,</a>
<a class="sourceLine" id="cb11-47" data-line-number="47">                             <span class="dt">timeDep.pExit=</span><span class="ot">FALSE</span>,</a>
<a class="sourceLine" id="cb11-48" data-line-number="48">                             <span class="dt">diff.pExit=</span><span class="ot">TRUE</span>,</a>
<a class="sourceLine" id="cb11-49" data-line-number="49">                             </a>
<a class="sourceLine" id="cb11-50" data-line-number="50">                             <span class="dt">pMove =</span> p_Move_fct,</a>
<a class="sourceLine" id="cb11-51" data-line-number="51">                             <span class="dt">param.pMove=</span><span class="ot">NA</span>,</a>
<a class="sourceLine" id="cb11-52" data-line-number="52">                             <span class="dt">timeDep.pMove=</span><span class="ot">FALSE</span>,</a>
<a class="sourceLine" id="cb11-53" data-line-number="53">                             <span class="dt">diff.pMove=</span><span class="ot">FALSE</span>,</a>
<a class="sourceLine" id="cb11-54" data-line-number="54">                             </a>
<a class="sourceLine" id="cb11-55" data-line-number="55">                             <span class="dt">nContact=</span>n_contact_fct,</a>
<a class="sourceLine" id="cb11-56" data-line-number="56">                             <span class="dt">param.nContact=</span><span class="ot">NA</span>,</a>
<a class="sourceLine" id="cb11-57" data-line-number="57">                             <span class="dt">timeDep.nContact=</span><span class="ot">FALSE</span>,</a>
<a class="sourceLine" id="cb11-58" data-line-number="58">                             <span class="dt">diff.nContact=</span><span class="ot">FALSE</span>,</a>
<a class="sourceLine" id="cb11-59" data-line-number="59">                             </a>
<a class="sourceLine" id="cb11-60" data-line-number="60">                             <span class="dt">pTrans =</span> proba,</a>
<a class="sourceLine" id="cb11-61" data-line-number="61">                             <span class="dt">param.pTrans =</span> <span class="kw"><a href="https://rdrr.io/r/base/list.html">list</a></span>(<span class="dt">p_max=</span>p_max_fct,<span class="dt">t_incub=</span>t_incub_fct),</a>
<a class="sourceLine" id="cb11-62" data-line-number="62">                             <span class="dt">timeDep.pTrans=</span><span class="ot">FALSE</span>,</a>
<a class="sourceLine" id="cb11-63" data-line-number="63">                             <span class="dt">diff.pTrans=</span><span class="ot">FALSE</span>,</a>
<a class="sourceLine" id="cb11-64" data-line-number="64">                             </a>
<a class="sourceLine" id="cb11-65" data-line-number="65">                             <span class="dt">prefix.host=</span><span class="st">"H"</span>,</a>
<a class="sourceLine" id="cb11-66" data-line-number="66">                             <span class="dt">print.progress=</span><span class="ot">FALSE</span>,</a>
<a class="sourceLine" id="cb11-67" data-line-number="67">                             <span class="dt">print.step=</span><span class="dv">10</span>)</a>
<a class="sourceLine" id="cb11-68" data-line-number="68"><span class="co">#&gt; Starting the simulation</span></a>
<a class="sourceLine" id="cb11-69" data-line-number="69"><span class="co">#&gt; Initializing ...</span></a>
<a class="sourceLine" id="cb11-70" data-line-number="70"><span class="co">#&gt;  running ...</span></a>
<a class="sourceLine" id="cb11-71" data-line-number="71"><span class="co">#&gt; done. </span></a>
<a class="sourceLine" id="cb11-72" data-line-number="72"><span class="co">#&gt; The simulation has run for 36 units of time and a total of 307 hosts have been infected.</span></a></code></pre></div>
<p>Once the simulation has finished, it reports the number of time units for which the simulation has run (36), and the maximum number of infected hosts (307). Note that the simulation has stopped here before reaching <code>length.sim</code> as it has crossed the <code>max.infected</code> threshold set at 300.</p>
</div>
</div>
<div id="dual-host-1" class="section level2">
<h2 class="hasAnchor">
<a href="#dual-host-1" class="anchor"></a>Dual host</h2>
<p>Setting up a dual host simulation is similar to the single host version described above, but each parameter has to be provided for both hosts. Here, we choose for Host A the same parameters as the single / only host above. Host B will have sightly different parameters:</p>
<div id="pexit-b" class="section level3">
<h3 class="hasAnchor">
<a href="#pexit-b" class="anchor"></a>pExit.B</h3>
<p>For <code>pExit.B</code>, we choose a value that depends on the “absolute” time of the simulation, for example cyclic climatic conditions (temperature). In that case, the function’s arguments should be <code>t</code> and <code>prestime</code> (the “absolute” time of the simulation), in that order:</p>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb12-1" data-line-number="1">p_Exit_fctB  &lt;-<span class="st"> </span><span class="cf">function</span>(t,prestime){(<span class="kw"><a href="https://rdrr.io/r/base/Trig.html">sin</a></span>(prestime<span class="op">/</span>(<span class="dv">2</span><span class="op">*</span>pi<span class="op">*</span><span class="dv">10</span>))<span class="op">+</span><span class="dv">1</span>)<span class="op">/</span><span class="dv">16</span>} <span class="co">#for a periodic function</span></a></code></pre></div>
<p>The values of <code>pExit.B</code> across the “absolute time” of the simulation will be the following:</p>
<p><img src="discrete_files/figure-html/pExit2-dual-1.png" width="700"></p>
<p>Since <code>pExit.B</code> is dependent of the simulation’s time, do not forget to set <code>timeDep.pExit.B</code> to <code>TRUE</code>. Since there are no individual-based parameters nor is there influence of the host’s location, we set <code>param.pExit.B=NA</code> and <code>diff.pExit.B=NA</code>.</p>
</div>
<div id="pmove-b" class="section level3">
<h3 class="hasAnchor">
<a href="#pmove-b" class="anchor"></a>pMove.B</h3>
<p>We will assume here that the hosts B do not move. <code>pMove.B</code> will then be set to <code>NA</code>.</p>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb13-1" data-line-number="1">p_Move_fct.B  &lt;-<span class="st"> </span><span class="ot">NA</span></a></code></pre></div>
<p>Since <code>pMove.B</code> is not dependent on the location, <code>diff.pMove.B=FALSE</code>. Similarly, there is no use of the “absolute” time of the simulation nor individual-based parameters, so <code>param.pMove.B=NA</code>, and <code>timeDep.pMove.B=FALSE</code>.</p>
</div>
<div id="ncontact-b" class="section level3">
<h3 class="hasAnchor">
<a href="#ncontact-b" class="anchor"></a>nContact.B</h3>
<p>For <code>nContact.B</code>, we choose a constant function that will sample a value out of a provided list of probabilities:</p>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb14-1" data-line-number="1">n_contact_fct.B =<span class="st"> </span><span class="cf">function</span>(t){<span class="kw"><a href="https://rdrr.io/r/base/sample.html">sample</a></span>(<span class="kw"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="dv">0</span>,<span class="dv">1</span>,<span class="dv">2</span>),<span class="dv">1</span>,<span class="dt">prob=</span><span class="kw"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="fl">0.6</span>,<span class="fl">0.3</span>,<span class="fl">0.1</span>))}</a></code></pre></div>
<p>The distribution of <code>nContact.B</code> looks as follows:</p>
<p><img src="discrete_files/figure-html/nContact2.B-1.png" width="700"></p>
<p>At each time and for each infected host, <code>nContact.B</code> will be drawn anew. Remember that <code>nContact.B</code>, like the other core functions has to be function of <code>t</code>, even if <code>t</code> is not used. Since <code>nContact.B</code> is constant here, there is no use of the “absolute” time of the simulation, the host’s location, nor individual-based parameters. Hence, <code>param.nContact.B=NA</code>, <code>timeDep.nContact.B=FALSE</code> and <code>diff.nContact.B=FALSE</code>.</p>
</div>
<div id="ptrans-b" class="section level3">
<h3 class="hasAnchor">
<a href="#ptrans-b" class="anchor"></a>pTrans.B</h3>
<p>We choose <code>pTrans.B</code> in the form of a Gaussian function. It will reach its maximum value at a certain time point (mean) after initial infection and will subsequently decrease until it reaches 0:</p>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb15-1" data-line-number="1">p_Trans_fct.B &lt;-<span class="st"> </span><span class="cf">function</span>(t, max.time){</a>
<a class="sourceLine" id="cb15-2" data-line-number="2">  <span class="kw"><a href="https://rdrr.io/r/stats/Normal.html">dnorm</a></span>(t, <span class="dt">mean=</span>max.time, <span class="dt">sd=</span><span class="dv">2</span>)<span class="op">*</span><span class="dv">5</span></a>
<a class="sourceLine" id="cb15-3" data-line-number="3">}</a></code></pre></div>
<p>Because each host is different (slightly different biotic and abiotic factors), you can expect each host to exhibit differences in the dynamics of infection, and hence the probability of transmission over time. Thus, <code>max.time</code> will be sampled for each host individually according to a certain distribution. <code>max.time</code> will be sampled from a normal distribution of parameters <span class="math inline">\(mean\)</span> = 5 and <span class="math inline">\(sd\)</span> = 1:</p>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb16-1" data-line-number="1">max.time_fct &lt;-<span class="st"> </span><span class="cf">function</span>(x){<span class="kw"><a href="https://rdrr.io/r/stats/Normal.html">rnorm</a></span>(x,<span class="dt">mean =</span> <span class="dv">5</span>,<span class="dt">sd=</span><span class="dv">1</span>)}</a></code></pre></div>
<p>Note again that here <code>max.time</code> is a function of <code>x</code> and not <code>t</code> (not a core function but individual-based parameters), and <code>x</code> enters the function as the number of draws to make.</p>
<p>Taken together, the profile for <code>pTrans</code> for a subset of 200 individuals in the population will look as follow:</p>
<p><img src="discrete_files/figure-html/pTrans3.B-1.png" width="700"></p>
<p>Since <code>pTrans.B</code> is not dependent on the “absolute” time of the simulation, <code>timeDep.pTrans.B=FALSE</code>. However, since we make use of individual-based parameters, we have to provide a <code>param.pTrans</code> as a list of functions. The name of each element of the list should have the same name as the core function (here <code>pTrans.B</code>) uses as argument, as shown here:</p>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb17-1" data-line-number="1">max.time_fct &lt;-<span class="st"> </span><span class="cf">function</span>(x){<span class="kw"><a href="https://rdrr.io/r/stats/Normal.html">rnorm</a></span>(x,<span class="dt">mean =</span> <span class="dv">5</span>,<span class="dt">sd=</span><span class="dv">1</span>)}</a>
<a class="sourceLine" id="cb17-2" data-line-number="2"></a>
<a class="sourceLine" id="cb17-3" data-line-number="3">param_pTrans.B =<span class="st"> </span><span class="kw"><a href="https://rdrr.io/r/base/list.html">list</a></span>(<span class="dt">max.time=</span>max.time_fct)</a></code></pre></div>
</div>
<div id="running-1" class="section level3">
<h3 class="hasAnchor">
<a href="#running-1" class="anchor"></a>Running</h3>
<p>Once <code>nosoiSim</code> is set up, you can run the simulation (here the “seed” ensures that you will get the same results as in this tutorial).</p>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb18-1" data-line-number="1"><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span>(nosoi)</a>
<a class="sourceLine" id="cb18-2" data-line-number="2"></a>
<a class="sourceLine" id="cb18-3" data-line-number="3"><span class="co">#Transition matrix</span></a>
<a class="sourceLine" id="cb18-4" data-line-number="4">transition.matrix &lt;-<span class="st"> </span><span class="kw"><a href="https://rdrr.io/r/base/matrix.html">matrix</a></span>(<span class="kw"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="dv">0</span>,<span class="fl">0.2</span>,<span class="fl">0.4</span>,<span class="fl">0.5</span>,<span class="dv">0</span>,<span class="fl">0.6</span>,<span class="fl">0.5</span>,<span class="fl">0.8</span>,<span class="dv">0</span>),<span class="dt">nrow =</span> <span class="dv">3</span>, <span class="dt">ncol =</span> <span class="dv">3</span>,<span class="dt">dimnames=</span><span class="kw"><a href="https://rdrr.io/r/base/list.html">list</a></span>(<span class="kw"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="st">"A"</span>,<span class="st">"B"</span>,<span class="st">"C"</span>),<span class="kw"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="st">"A"</span>,<span class="st">"B"</span>,<span class="st">"C"</span>)))</a>
<a class="sourceLine" id="cb18-5" data-line-number="5"></a>
<a class="sourceLine" id="cb18-6" data-line-number="6"><span class="co">#Host A -----------------------------------</span></a>
<a class="sourceLine" id="cb18-7" data-line-number="7"></a>
<a class="sourceLine" id="cb18-8" data-line-number="8"><span class="co">#pExit</span></a>
<a class="sourceLine" id="cb18-9" data-line-number="9">p_Exit_fct  &lt;-<span class="st"> </span><span class="cf">function</span>(t,current.in){</a>
<a class="sourceLine" id="cb18-10" data-line-number="10">  <span class="cf">if</span>(current.in<span class="op">==</span><span class="st">"A"</span>){<span class="kw"><a href="https://rdrr.io/r/base/function.html">return</a></span>(<span class="fl">0.02</span>)}</a>
<a class="sourceLine" id="cb18-11" data-line-number="11">  <span class="cf">if</span>(current.in<span class="op">==</span><span class="st">"B"</span>){<span class="kw"><a href="https://rdrr.io/r/base/function.html">return</a></span>(<span class="fl">0.05</span>)}</a>
<a class="sourceLine" id="cb18-12" data-line-number="12">  <span class="cf">if</span>(current.in<span class="op">==</span><span class="st">"C"</span>){<span class="kw"><a href="https://rdrr.io/r/base/function.html">return</a></span>(<span class="fl">0.1</span>)}</a>
<a class="sourceLine" id="cb18-13" data-line-number="13">}</a>
<a class="sourceLine" id="cb18-14" data-line-number="14"></a>
<a class="sourceLine" id="cb18-15" data-line-number="15"><span class="co">#pMove</span></a>
<a class="sourceLine" id="cb18-16" data-line-number="16">p_Move_fct  &lt;-<span class="st"> </span><span class="cf">function</span>(t){<span class="kw"><a href="https://rdrr.io/r/base/function.html">return</a></span>(<span class="fl">0.1</span>)}</a>
<a class="sourceLine" id="cb18-17" data-line-number="17"></a>
<a class="sourceLine" id="cb18-18" data-line-number="18"><span class="co">#nContact</span></a>
<a class="sourceLine" id="cb18-19" data-line-number="19">n_contact_fct =<span class="st"> </span><span class="cf">function</span>(t){<span class="kw"><a href="https://rdrr.io/r/base/MathFun.html">abs</a></span>(<span class="kw"><a href="https://rdrr.io/r/base/Round.html">round</a></span>(<span class="kw"><a href="https://rdrr.io/r/stats/Normal.html">rnorm</a></span>(<span class="dv">1</span>, <span class="fl">0.5</span>, <span class="dv">1</span>), <span class="dv">0</span>))}</a>
<a class="sourceLine" id="cb18-20" data-line-number="20"></a>
<a class="sourceLine" id="cb18-21" data-line-number="21"><span class="co">#pTrans</span></a>
<a class="sourceLine" id="cb18-22" data-line-number="22">proba &lt;-<span class="st"> </span><span class="cf">function</span>(t,p_max,t_incub){</a>
<a class="sourceLine" id="cb18-23" data-line-number="23">  <span class="cf">if</span>(t <span class="op">&lt;=</span><span class="st"> </span>t_incub){p=<span class="dv">0</span>}</a>
<a class="sourceLine" id="cb18-24" data-line-number="24">  <span class="cf">if</span>(t <span class="op">&gt;=</span><span class="st"> </span>t_incub){p=p_max}</a>
<a class="sourceLine" id="cb18-25" data-line-number="25">  <span class="kw"><a href="https://rdrr.io/r/base/function.html">return</a></span>(p)</a>
<a class="sourceLine" id="cb18-26" data-line-number="26">}</a>
<a class="sourceLine" id="cb18-27" data-line-number="27"></a>
<a class="sourceLine" id="cb18-28" data-line-number="28">t_incub_fct &lt;-<span class="st"> </span><span class="cf">function</span>(x){<span class="kw"><a href="https://rdrr.io/r/stats/Normal.html">rnorm</a></span>(x,<span class="dt">mean =</span> <span class="dv">5</span>,<span class="dt">sd=</span><span class="dv">1</span>)}</a>
<a class="sourceLine" id="cb18-29" data-line-number="29">p_max_fct &lt;-<span class="st"> </span><span class="cf">function</span>(x){<span class="kw"><a href="https://rdrr.io/r/stats/Beta.html">rbeta</a></span>(x,<span class="dt">shape1 =</span> <span class="dv">5</span>,<span class="dt">shape2=</span><span class="dv">2</span>)}</a>
<a class="sourceLine" id="cb18-30" data-line-number="30"></a>
<a class="sourceLine" id="cb18-31" data-line-number="31">param_pTrans =<span class="st"> </span><span class="kw"><a href="https://rdrr.io/r/base/list.html">list</a></span>(<span class="dt">p_max=</span>p_max_fct,<span class="dt">t_incub=</span>t_incub_fct)</a>
<a class="sourceLine" id="cb18-32" data-line-number="32"></a>
<a class="sourceLine" id="cb18-33" data-line-number="33"><span class="co">#Host B -----------------------------------</span></a>
<a class="sourceLine" id="cb18-34" data-line-number="34"></a>
<a class="sourceLine" id="cb18-35" data-line-number="35"><span class="co">#pExit</span></a>
<a class="sourceLine" id="cb18-36" data-line-number="36">p_Exit_fct.B  &lt;-<span class="st"> </span><span class="cf">function</span>(t,prestime){(<span class="kw"><a href="https://rdrr.io/r/base/Trig.html">sin</a></span>(prestime<span class="op">/</span>(<span class="dv">2</span><span class="op">*</span>pi<span class="op">*</span><span class="dv">10</span>))<span class="op">+</span><span class="dv">1</span>)<span class="op">/</span><span class="dv">16</span>}</a>
<a class="sourceLine" id="cb18-37" data-line-number="37"></a>
<a class="sourceLine" id="cb18-38" data-line-number="38"><span class="co">#pMove</span></a>
<a class="sourceLine" id="cb18-39" data-line-number="39">p_Move_fct.B  &lt;-<span class="st"> </span><span class="ot">NA</span></a>
<a class="sourceLine" id="cb18-40" data-line-number="40"></a>
<a class="sourceLine" id="cb18-41" data-line-number="41"><span class="co">#nContact</span></a>
<a class="sourceLine" id="cb18-42" data-line-number="42">n_contact_fct.B =<span class="st"> </span><span class="cf">function</span>(t){<span class="kw"><a href="https://rdrr.io/r/base/sample.html">sample</a></span>(<span class="kw"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="dv">0</span>,<span class="dv">1</span>,<span class="dv">2</span>),<span class="dv">1</span>,<span class="dt">prob=</span><span class="kw"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="fl">0.6</span>,<span class="fl">0.3</span>,<span class="fl">0.1</span>))}</a>
<a class="sourceLine" id="cb18-43" data-line-number="43"></a>
<a class="sourceLine" id="cb18-44" data-line-number="44"><span class="co">#pTrans</span></a>
<a class="sourceLine" id="cb18-45" data-line-number="45">p_Trans_fct.B &lt;-<span class="st"> </span><span class="cf">function</span>(t, max.time){</a>
<a class="sourceLine" id="cb18-46" data-line-number="46">  <span class="kw"><a href="https://rdrr.io/r/stats/Normal.html">dnorm</a></span>(t, <span class="dt">mean=</span>max.time, <span class="dt">sd=</span><span class="dv">2</span>)<span class="op">*</span><span class="dv">5</span></a>
<a class="sourceLine" id="cb18-47" data-line-number="47">}</a>
<a class="sourceLine" id="cb18-48" data-line-number="48"> </a>
<a class="sourceLine" id="cb18-49" data-line-number="49">max.time_fct &lt;-<span class="st"> </span><span class="cf">function</span>(x){<span class="kw"><a href="https://rdrr.io/r/stats/Normal.html">rnorm</a></span>(x,<span class="dt">mean =</span> <span class="dv">5</span>,<span class="dt">sd=</span><span class="dv">1</span>)}</a>
<a class="sourceLine" id="cb18-50" data-line-number="50"></a>
<a class="sourceLine" id="cb18-51" data-line-number="51">param_pTrans.B =<span class="st"> </span><span class="kw"><a href="https://rdrr.io/r/base/list.html">list</a></span>(<span class="dt">max.time=</span>max.time_fct)</a>
<a class="sourceLine" id="cb18-52" data-line-number="52"></a>
<a class="sourceLine" id="cb18-53" data-line-number="53"><span class="co"># Starting the simulation ------------------------------------</span></a>
<a class="sourceLine" id="cb18-54" data-line-number="54"></a>
<a class="sourceLine" id="cb18-55" data-line-number="55"><span class="kw"><a href="https://rdrr.io/r/base/Random.html">set.seed</a></span>(<span class="dv">60</span>)</a>
<a class="sourceLine" id="cb18-56" data-line-number="56">SimulationDual &lt;-<span class="st"> </span><span class="kw"><a href="../reference/nosoiSim.html">nosoiSim</a></span>(<span class="dt">type=</span><span class="st">"dual"</span>, <span class="dt">popStructure=</span><span class="st">"discrete"</span>,</a>
<a class="sourceLine" id="cb18-57" data-line-number="57">                           <span class="dt">length.sim=</span><span class="dv">300</span>, </a>
<a class="sourceLine" id="cb18-58" data-line-number="58">                           <span class="dt">max.infected.A=</span><span class="dv">100</span>,</a>
<a class="sourceLine" id="cb18-59" data-line-number="59">                           <span class="dt">max.infected.B=</span><span class="dv">200</span>,</a>
<a class="sourceLine" id="cb18-60" data-line-number="60">                           <span class="dt">init.individuals.A=</span><span class="dv">1</span>,</a>
<a class="sourceLine" id="cb18-61" data-line-number="61">                           <span class="dt">init.individuals.B=</span><span class="dv">0</span>,</a>
<a class="sourceLine" id="cb18-62" data-line-number="62">                           <span class="dt">init.structure.A=</span><span class="st">"A"</span>,</a>
<a class="sourceLine" id="cb18-63" data-line-number="63">                           <span class="dt">init.structure.B=</span><span class="ot">NA</span>,</a>
<a class="sourceLine" id="cb18-64" data-line-number="64">                           <span class="dt">structure.matrix.A=</span>transition.matrix,</a>
<a class="sourceLine" id="cb18-65" data-line-number="65">                           <span class="dt">structure.matrix.B=</span>transition.matrix,</a>
<a class="sourceLine" id="cb18-66" data-line-number="66">                           </a>
<a class="sourceLine" id="cb18-67" data-line-number="67">                           <span class="dt">pExit.A =</span> p_Exit_fct,</a>
<a class="sourceLine" id="cb18-68" data-line-number="68">                           <span class="dt">param.pExit.A=</span><span class="ot">NA</span>,</a>
<a class="sourceLine" id="cb18-69" data-line-number="69">                           <span class="dt">timeDep.pExit.A=</span><span class="ot">FALSE</span>,</a>
<a class="sourceLine" id="cb18-70" data-line-number="70">                           <span class="dt">diff.pExit.A=</span><span class="ot">TRUE</span>,</a>
<a class="sourceLine" id="cb18-71" data-line-number="71">                           </a>
<a class="sourceLine" id="cb18-72" data-line-number="72">                           <span class="dt">pMove.A =</span> p_Move_fct,</a>
<a class="sourceLine" id="cb18-73" data-line-number="73">                           <span class="dt">param.pMove.A=</span><span class="ot">NA</span>,</a>
<a class="sourceLine" id="cb18-74" data-line-number="74">                           <span class="dt">timeDep.pMove.A=</span><span class="ot">FALSE</span>,</a>
<a class="sourceLine" id="cb18-75" data-line-number="75">                           <span class="dt">diff.pMove.A=</span><span class="ot">FALSE</span>,</a>
<a class="sourceLine" id="cb18-76" data-line-number="76">                           </a>
<a class="sourceLine" id="cb18-77" data-line-number="77">                           <span class="dt">nContact.A=</span>n_contact_fct,</a>
<a class="sourceLine" id="cb18-78" data-line-number="78">                           <span class="dt">param.nContact.A=</span><span class="ot">NA</span>,</a>
<a class="sourceLine" id="cb18-79" data-line-number="79">                           <span class="dt">timeDep.nContact.A=</span><span class="ot">FALSE</span>,</a>
<a class="sourceLine" id="cb18-80" data-line-number="80">                           <span class="dt">diff.nContact.A=</span><span class="ot">FALSE</span>,</a>
<a class="sourceLine" id="cb18-81" data-line-number="81">                           </a>
<a class="sourceLine" id="cb18-82" data-line-number="82">                           <span class="dt">pTrans.A =</span> proba,</a>
<a class="sourceLine" id="cb18-83" data-line-number="83">                           <span class="dt">param.pTrans.A =</span> <span class="kw"><a href="https://rdrr.io/r/base/list.html">list</a></span>(<span class="dt">p_max=</span>p_max_fct,<span class="dt">t_incub=</span>t_incub_fct),</a>
<a class="sourceLine" id="cb18-84" data-line-number="84">                           <span class="dt">timeDep.pTrans.A=</span><span class="ot">FALSE</span>,</a>
<a class="sourceLine" id="cb18-85" data-line-number="85">                           <span class="dt">diff.pTrans.A=</span><span class="ot">FALSE</span>,</a>
<a class="sourceLine" id="cb18-86" data-line-number="86">                           <span class="dt">prefix.host.A=</span><span class="st">"H"</span>,</a>
<a class="sourceLine" id="cb18-87" data-line-number="87">                           </a>
<a class="sourceLine" id="cb18-88" data-line-number="88">                           <span class="dt">pExit.B =</span> p_Exit_fct.B,</a>
<a class="sourceLine" id="cb18-89" data-line-number="89">                           <span class="dt">param.pExit.B=</span><span class="ot">NA</span>,</a>
<a class="sourceLine" id="cb18-90" data-line-number="90">                           <span class="dt">timeDep.pExit.B=</span><span class="ot">TRUE</span>,</a>
<a class="sourceLine" id="cb18-91" data-line-number="91">                           <span class="dt">diff.pExit.B=</span><span class="ot">FALSE</span>,</a>
<a class="sourceLine" id="cb18-92" data-line-number="92">                           </a>
<a class="sourceLine" id="cb18-93" data-line-number="93">                           <span class="dt">pMove.B =</span> p_Move_fct.B,</a>
<a class="sourceLine" id="cb18-94" data-line-number="94">                           <span class="dt">param.pMove.B=</span><span class="ot">NA</span>,</a>
<a class="sourceLine" id="cb18-95" data-line-number="95">                           <span class="dt">timeDep.pMove.B=</span><span class="ot">FALSE</span>,</a>
<a class="sourceLine" id="cb18-96" data-line-number="96">                           <span class="dt">diff.pMove.B=</span><span class="ot">FALSE</span>,</a>
<a class="sourceLine" id="cb18-97" data-line-number="97">                           </a>
<a class="sourceLine" id="cb18-98" data-line-number="98">                           <span class="dt">nContact.B=</span>n_contact_fct.B,</a>
<a class="sourceLine" id="cb18-99" data-line-number="99">                           <span class="dt">param.nContact.B=</span><span class="ot">NA</span>,</a>
<a class="sourceLine" id="cb18-100" data-line-number="100">                           <span class="dt">timeDep.nContact.B=</span><span class="ot">FALSE</span>,</a>
<a class="sourceLine" id="cb18-101" data-line-number="101">                           <span class="dt">diff.nContact.B=</span><span class="ot">FALSE</span>,</a>
<a class="sourceLine" id="cb18-102" data-line-number="102">                           </a>
<a class="sourceLine" id="cb18-103" data-line-number="103">                           <span class="dt">pTrans.B =</span> p_Trans_fct.B,</a>
<a class="sourceLine" id="cb18-104" data-line-number="104">                           <span class="dt">param.pTrans.B =</span> param_pTrans.B,</a>
<a class="sourceLine" id="cb18-105" data-line-number="105">                           <span class="dt">timeDep.pTrans.B=</span><span class="ot">FALSE</span>,</a>
<a class="sourceLine" id="cb18-106" data-line-number="106">                           <span class="dt">diff.pTrans.B=</span><span class="ot">FALSE</span>,</a>
<a class="sourceLine" id="cb18-107" data-line-number="107">                           <span class="dt">prefix.host.B=</span><span class="st">"V"</span>,</a>
<a class="sourceLine" id="cb18-108" data-line-number="108">                           </a>
<a class="sourceLine" id="cb18-109" data-line-number="109">                           <span class="dt">print.progress=</span><span class="ot">FALSE</span>)</a>
<a class="sourceLine" id="cb18-110" data-line-number="110"><span class="co">#&gt; Starting the simulation</span></a>
<a class="sourceLine" id="cb18-111" data-line-number="111"><span class="co">#&gt; Initializing ... running ...</span></a>
<a class="sourceLine" id="cb18-112" data-line-number="112"><span class="co">#&gt; done. </span></a>
<a class="sourceLine" id="cb18-113" data-line-number="113"><span class="co">#&gt; The simulation has run for 34 units of time and a total of 106 (A) and 129 (B) hosts have been infected.</span></a></code></pre></div>
<p>Once the simulation has finished, it reports the number of time units for which the simulation has run (34), and the maximum number of infected hosts A (106) and hosts B (129). Note that the simulation has stopped here before reaching <code>length.sim</code> as it has crossed the <code>max.infected.A</code> threshold set at 100.</p>
</div>
</div>
</div>
<div id="going-further" class="section level1">
<h1 class="hasAnchor">
<a href="#going-further" class="anchor"></a>Going further</h1>
<p>To analyze and visualize your <code>nosoi</code> simulation output, you can have a look on <a href="https://slequime.github.io/nosoi/articles/examples/viz.html">this page</a>.</p>
<p>A practical example using a dual host type of simulation with a discrete population structure is also available:</p>
<ul>
<li>
<a href="https://slequime.github.io/nosoi/articles/examples/dengue.html">Spread of dengue virus in a discrete space</a>.</li>
</ul>
</div>
  </div>

  <div class="col-md-3 hidden-xs hidden-sm" id="sidebar">

        <div id="tocnav">
      <h2 class="hasAnchor">
<a href="#tocnav" class="anchor"></a>Contents</h2>
      <ul class="nav nav-pills nav-stacked">
<li><a href="#structure-of-the-population">Structure of the population</a></li>
      <li>
<a href="#setting-up-the-simulation">Setting up the simulation</a><ul class="nav nav-pills nav-stacked">
<li><a href="#general-parameters">General parameters</a></li>
      <li><a href="#core-functions">Core functions</a></li>
      <li><a href="#miscellaneous">Miscellaneous</a></li>
      <li><a href="#dual-host">Dual host</a></li>
      </ul>
</li>
      <li>
<a href="#running-nosoi">Running <code>nosoi</code></a><ul class="nav nav-pills nav-stacked">
<li><a href="#single-host">Single host</a></li>
      <li><a href="#dual-host-1">Dual host</a></li>
      </ul>
</li>
      <li><a href="#going-further">Going further</a></li>
      </ul>
</div>
      </div>

</div>



      <footer><div class="copyright">
  <p>Developed by Sebastian Lequime, Paul Bastide, Simon Dellicour, Philippe Lemey, Guy Baele.</p>
</div>

<div class="pkgdown">
  <p>Site built with <a href="https://pkgdown.r-lib.org/">pkgdown</a> 1.4.1.</p>
</div>

      </footer>
</div>

  


  </body>
</html>
